
//Icon
#define MainExeIconID           1

//Menu
#define MainMenuID              1


//Main Window IDs
#define StatusBarID             100     //메인 윈도우의 아래 상태바 ID
#define TrackBarID              101     //메인 윈도우의 트랙바 ID
#define SettingCmdID            102
#define ExitCmdID               103
#define AboutCmdID              104


//트랙바 범위 설정 페이지
#define SetTbRangeDialog        1
#define TbRangeMinEBID          100
#define TbRangeMaxEBID          101


//트랙바 페이지 라인 설정 페이지
#define SetTbPageLineDialog     2
#define TbPageSizeEBID          100
#define TbLineSizeEBID          101


//About대화상자
#define AboutDialog             3
